--------------------------------------------------------------------------------
-- Corlix Hub · Histórico de Carreira
-- 01 · DDL: tabelas, constraints, índices e comentários
--
-- Reexecutável: usa CREATE ... IF NOT EXISTS (Oracle 23ai). Em uma segunda
-- execução nada é recriado; COMMENT ON apenas sobrescreve o texto.
--
-- Reaproveita (não recria): EMPRESA, COLABORADOR, DEPARTAMENTO e CARGO.
-- Todas as tabelas novas têm ID_EMPRESA (isolamento multi-tenant).
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- 1. CONFIG_CARREIRA · parâmetros do módulo por empresa
--------------------------------------------------------------------------------
create table if not exists config_carreira (
  id_empresa       number                                   not null,
  qt_dias_futuro   number(4)    default 30                  not null,
  ds_fuso_horario  varchar2(64) default 'America/Sao_Paulo' not null,
  fl_comunicado_automatico boolean default true not null,
  dt_criacao       timestamp with time zone default systimestamp not null,
  usr_criacao      varchar2(255) default coalesce(sys_context('APEX$SESSION', 'APP_USER'), sys_context('USERENV', 'SESSION_USER')) not null,
  dt_alteracao     timestamp with time zone,
  usr_alteracao    varchar2(255),
  constraint config_carreira_pk         primary key (id_empresa),
  constraint config_carreira_empresa_fk foreign key (id_empresa) references empresa (id_empresa),
  constraint config_carreira_dias_ck    check (qt_dias_futuro between 0 and 3650)
);

comment on table  config_carreira                 is 'Parâmetros do módulo Histórico de Carreira por empresa. Sem linha para a empresa, valem os padrões do package.';
comment on column config_carreira.id_empresa      is 'Empresa dona dos parâmetros (PK e FK para EMPRESA).';
comment on column config_carreira.qt_dias_futuro  is 'Quantos dias no futuro uma movimentação pode ter como data efetiva.';
comment on column config_carreira.ds_fuso_horario is 'Fuso horário (IANA) usado para calcular "hoje" na empresa. O Autonomous Database roda em UTC.';
comment on column config_carreira.fl_comunicado_automatico is 'Se admissões, promoções e transferências efetivadas publicam um comunicado para a equipe.';
comment on column config_carreira.dt_criacao      is 'Auditoria: data/hora de criação.';
comment on column config_carreira.usr_criacao     is 'Auditoria: usuário que criou.';
comment on column config_carreira.dt_alteracao    is 'Auditoria: data/hora da última alteração.';
comment on column config_carreira.usr_alteracao   is 'Auditoria: usuário da última alteração.';


--------------------------------------------------------------------------------
-- 2. TIPO_MOVIMENTACAO · domínio parametrizável por empresa
--------------------------------------------------------------------------------
create table if not exists tipo_movimentacao (
  id_tipo_movimentacao number generated by default on null as identity,
  id_empresa           number         not null,
  cd_tipo              varchar2(30)   not null,
  ds_tipo              varchar2(100)  not null,
  ds_icone             varchar2(100),
  ds_cor               varchar2(50),
  nr_ordem             number(3)      default 100 not null,
  fl_ativo             boolean        default true not null,
  dt_criacao           timestamp with time zone default systimestamp not null,
  usr_criacao          varchar2(255) default coalesce(sys_context('APEX$SESSION', 'APP_USER'), sys_context('USERENV', 'SESSION_USER')) not null,
  dt_alteracao         timestamp with time zone,
  usr_alteracao        varchar2(255),
  constraint tipo_movimentacao_pk         primary key (id_tipo_movimentacao),
  constraint tipo_movimentacao_uk         unique (id_empresa, cd_tipo),
  constraint tipo_movimentacao_empresa_fk foreign key (id_empresa) references empresa (id_empresa),
  constraint tipo_movimentacao_cd_ck      check (regexp_like(cd_tipo, '^[A-Z][A-Z0-9_]*$'))
);

comment on table  tipo_movimentacao                      is 'Tipos de movimentação de carreira por empresa (ADMISSAO, PROMOCAO etc.). Cada empresa pode renomear, recolorir ou desativar.';
comment on column tipo_movimentacao.id_tipo_movimentacao is 'PK (identity).';
comment on column tipo_movimentacao.id_empresa           is 'Empresa dona do tipo (FK para EMPRESA).';
comment on column tipo_movimentacao.cd_tipo              is 'Código interno, usado pelas regras do package. Os códigos padrão têm comportamento próprio; códigos novos são tratados como eventos genéricos.';
comment on column tipo_movimentacao.ds_tipo              is 'Descrição exibida ao usuário.';
comment on column tipo_movimentacao.ds_icone             is 'Classe Font APEX do ícone (ex.: fa-arrow-circle-up).';
comment on column tipo_movimentacao.ds_cor               is 'Classe de cor do Universal Theme (ex.: u-success, u-color-5).';
comment on column tipo_movimentacao.nr_ordem             is 'Ordem de exibição nas listas.';
comment on column tipo_movimentacao.fl_ativo             is 'Se o tipo pode ser usado em novos lançamentos.';
comment on column tipo_movimentacao.dt_criacao           is 'Auditoria: data/hora de criação.';
comment on column tipo_movimentacao.usr_criacao          is 'Auditoria: usuário que criou.';
comment on column tipo_movimentacao.dt_alteracao         is 'Auditoria: data/hora da última alteração.';
comment on column tipo_movimentacao.usr_alteracao        is 'Auditoria: usuário da última alteração.';


--------------------------------------------------------------------------------
-- 3. HISTORICO_CARREIRA · movimentações internas (fonte de verdade do RH)
--------------------------------------------------------------------------------
create table if not exists historico_carreira (
  id_historico_carreira    number generated always as identity,
  id_empresa               number        not null,
  id_colaborador           number        not null,
  id_tipo_movimentacao     number        not null,
  dt_efetiva               date          not null,
  id_cargo_anterior        number,
  id_departamento_anterior number,
  id_gestor_anterior       number,
  id_cargo_novo            number,
  id_departamento_novo     number,
  id_gestor_novo           number,
  vl_salario_anterior      number(12,2),
  vl_salario_novo          number(12,2),
  ds_motivo                varchar2(1000),
  ds_observacao            clob,
  st_registro              varchar2(10)  default 'RASCUNHO' not null,
  id_registro_estornado    number,
  id_comunicado            number,
  id_aprovador             number,
  dt_efetivacao            timestamp with time zone,
  usr_efetivacao           varchar2(255),
  dt_criacao               timestamp with time zone default systimestamp not null,
  usr_criacao              varchar2(255) default coalesce(sys_context('APEX$SESSION', 'APP_USER'), sys_context('USERENV', 'SESSION_USER')) not null,
  dt_alteracao             timestamp with time zone,
  usr_alteracao            varchar2(255),
  constraint historico_carreira_pk              primary key (id_historico_carreira),
  constraint historico_carreira_empresa_fk      foreign key (id_empresa)               references empresa (id_empresa),
  constraint historico_carreira_colab_fk        foreign key (id_colaborador)           references colaborador (id_colaborador),
  constraint historico_carreira_tipo_fk         foreign key (id_tipo_movimentacao)     references tipo_movimentacao (id_tipo_movimentacao),
  constraint historico_carreira_cargo_ant_fk    foreign key (id_cargo_anterior)        references cargo (id_cargo),
  constraint historico_carreira_depto_ant_fk    foreign key (id_departamento_anterior) references departamento (id_departamento),
  constraint historico_carreira_gestor_ant_fk   foreign key (id_gestor_anterior)       references colaborador (id_colaborador),
  constraint historico_carreira_cargo_novo_fk   foreign key (id_cargo_novo)            references cargo (id_cargo),
  constraint historico_carreira_depto_novo_fk   foreign key (id_departamento_novo)     references departamento (id_departamento),
  constraint historico_carreira_gestor_novo_fk  foreign key (id_gestor_novo)           references colaborador (id_colaborador),
  constraint historico_carreira_estorno_fk      foreign key (id_registro_estornado)    references historico_carreira (id_historico_carreira),
  constraint historico_carreira_comunicado_fk   foreign key (id_comunicado)            references comunicado (id_comunicado),
  constraint historico_carreira_aprovador_fk    foreign key (id_aprovador)             references colaborador (id_colaborador),
  -- um lançamento só pode ser estornado uma vez
  constraint historico_carreira_estorno_uk      unique (id_registro_estornado),
  constraint historico_carreira_st_ck           check (st_registro in ('RASCUNHO', 'EFETIVADO', 'ESTORNADO')),
  constraint historico_carreira_estorno_ck      check (id_registro_estornado is null
                                                       or (st_registro = 'EFETIVADO' and id_registro_estornado <> id_historico_carreira)),
  constraint historico_carreira_efetivacao_ck   check (st_registro = 'RASCUNHO' or dt_efetivacao is not null),
  constraint historico_carreira_sal_ant_ck      check (vl_salario_anterior >= 0),
  constraint historico_carreira_sal_novo_ck     check (vl_salario_novo >= 0),
  constraint historico_carreira_gestor_ck       check (id_gestor_novo is null or id_gestor_novo <> id_colaborador),
  constraint historico_carreira_aprovador_ck    check (id_aprovador is null or id_aprovador <> id_colaborador)
);

-- Migração: bancos instalados antes da coluna ID_APROVADOR (reexecutável)
declare
  l_qt pls_integer;
begin
  select count(*) into l_qt
    from user_tab_columns
   where table_name = 'HISTORICO_CARREIRA' and column_name = 'ID_APROVADOR';
  if l_qt = 0 then
    execute immediate 'alter table historico_carreira add (id_aprovador number)';
  end if;

  select count(*) into l_qt
    from user_constraints
   where table_name = 'HISTORICO_CARREIRA' and constraint_name = 'HISTORICO_CARREIRA_APROVADOR_FK';
  if l_qt = 0 then
    execute immediate 'alter table historico_carreira add constraint historico_carreira_aprovador_fk '
                      || 'foreign key (id_aprovador) references colaborador (id_colaborador)';
  end if;

  select count(*) into l_qt
    from user_constraints
   where table_name = 'HISTORICO_CARREIRA' and constraint_name = 'HISTORICO_CARREIRA_APROVADOR_CK';
  if l_qt = 0 then
    execute immediate 'alter table historico_carreira add constraint historico_carreira_aprovador_ck '
                      || 'check (id_aprovador is null or id_aprovador <> id_colaborador)';
  end if;
end;
/

create index if not exists historico_carreira_emp_colab_ix on historico_carreira (id_empresa, id_colaborador);
create index if not exists historico_carreira_colab_dt_ix  on historico_carreira (id_colaborador, st_registro, dt_efetiva);
create index if not exists historico_carreira_emp_dt_ix    on historico_carreira (id_empresa, dt_efetiva);
create index if not exists historico_carreira_tipo_ix      on historico_carreira (id_tipo_movimentacao);
create index if not exists historico_carreira_cargo_ant_ix on historico_carreira (id_cargo_anterior);
create index if not exists historico_carreira_cargo_nov_ix on historico_carreira (id_cargo_novo);
create index if not exists historico_carreira_dep_ant_ix   on historico_carreira (id_departamento_anterior);
create index if not exists historico_carreira_dep_nov_ix   on historico_carreira (id_departamento_novo);
create index if not exists historico_carreira_ges_ant_ix   on historico_carreira (id_gestor_anterior);
create index if not exists historico_carreira_ges_nov_ix   on historico_carreira (id_gestor_novo);
create index if not exists historico_carreira_comunic_ix   on historico_carreira (id_comunicado);
create index if not exists historico_carreira_aprov_ix     on historico_carreira (id_aprovador);

comment on table  historico_carreira                          is 'Movimentações de carreira do colaborador. Imutável depois de EFETIVADO: correções são feitas por estorno + novo lançamento.';
comment on column historico_carreira.id_historico_carreira    is 'PK (identity).';
comment on column historico_carreira.id_empresa               is 'Empresa (tenant). Sempre igual à empresa do colaborador.';
comment on column historico_carreira.id_colaborador           is 'Colaborador movimentado (FK para COLABORADOR).';
comment on column historico_carreira.id_tipo_movimentacao     is 'Tipo da movimentação (FK para TIPO_MOVIMENTACAO da mesma empresa).';
comment on column historico_carreira.dt_efetiva               is 'Data em que a movimentação passa a valer.';
comment on column historico_carreira.id_cargo_anterior        is 'Cargo do colaborador antes da movimentação (snapshot gravado na efetivação).';
comment on column historico_carreira.id_departamento_anterior is 'Departamento antes da movimentação (snapshot gravado na efetivação).';
comment on column historico_carreira.id_gestor_anterior       is 'Gestor antes da movimentação (snapshot gravado na efetivação). Necessário para o estorno.';
comment on column historico_carreira.id_cargo_novo            is 'Cargo após a movimentação. Na efetivação recebe o cargo final, mesmo que não tenha mudado.';
comment on column historico_carreira.id_departamento_novo     is 'Departamento após a movimentação. Na efetivação recebe o departamento final.';
comment on column historico_carreira.id_gestor_novo           is 'Gestor após a movimentação (FK para COLABORADOR). Na efetivação recebe o gestor final.';
comment on column historico_carreira.vl_salario_anterior      is 'SENSÍVEL (LGPD). Salário antes da movimentação. Visível só para ADMIN_RH; acessos são registrados em LOG_ACESSO_SALARIAL.';
comment on column historico_carreira.vl_salario_novo          is 'SENSÍVEL (LGPD). Salário após a movimentação. Visível só para ADMIN_RH; acessos são registrados em LOG_ACESSO_SALARIAL.';
comment on column historico_carreira.ds_motivo                is 'Motivo da movimentação (ou do estorno, nos lançamentos de estorno).';
comment on column historico_carreira.ds_observacao            is 'Observações livres.';
comment on column historico_carreira.st_registro              is 'RASCUNHO (editável), EFETIVADO (imutável) ou ESTORNADO (efetivado que foi revertido).';
comment on column historico_carreira.id_registro_estornado    is 'Preenchido apenas nos lançamentos de estorno: aponta para o lançamento revertido (autorrelacionamento).';
comment on column historico_carreira.id_comunicado            is 'Comunicado publicado automaticamente para a equipe na efetivação (admissão, promoção, transferência).';
comment on column historico_carreira.id_aprovador             is 'Colaborador que aprovou a movimentação (em geral a gestão). Opcional; aparece como "Aprovado por" na linha do tempo. Não pode ser o próprio colaborador.';
comment on column historico_carreira.dt_efetivacao            is 'Data/hora em que o lançamento foi efetivado.';
comment on column historico_carreira.usr_efetivacao           is 'Usuário que efetivou o lançamento.';
comment on column historico_carreira.dt_criacao               is 'Auditoria: data/hora de criação.';
comment on column historico_carreira.usr_criacao              is 'Auditoria: usuário que criou.';
comment on column historico_carreira.dt_alteracao             is 'Auditoria: data/hora da última alteração.';
comment on column historico_carreira.usr_alteracao            is 'Auditoria: usuário da última alteração.';


--------------------------------------------------------------------------------
-- 4. FORMACAO_COLABORADOR · formações e certificações
--------------------------------------------------------------------------------
create table if not exists formacao_colaborador (
  id_formacao      number generated always as identity,
  id_empresa       number         not null,
  id_colaborador   number         not null,
  tp_formacao      varchar2(20)   not null,
  ds_instituicao   varchar2(200)  not null,
  ds_titulo        varchar2(300)  not null,
  dt_inicio        date,
  dt_conclusao     date,
  dt_validade      date,
  nr_carga_horaria number(6,1),
  bl_anexo         blob,
  ds_mime_type     varchar2(255),
  ds_nome_arquivo  varchar2(400),
  ds_link          varchar2(1000),
  dt_criacao       timestamp with time zone default systimestamp not null,
  usr_criacao      varchar2(255) default coalesce(sys_context('APEX$SESSION', 'APP_USER'), sys_context('USERENV', 'SESSION_USER')) not null,
  dt_alteracao     timestamp with time zone,
  usr_alteracao    varchar2(255),
  constraint formacao_colaborador_pk         primary key (id_formacao),
  constraint formacao_colaborador_empresa_fk foreign key (id_empresa)     references empresa (id_empresa),
  constraint formacao_colaborador_colab_fk   foreign key (id_colaborador) references colaborador (id_colaborador),
  constraint formacao_colaborador_tp_ck      check (tp_formacao in ('GRADUACAO', 'POS', 'MBA', 'CURSO', 'CERTIFICACAO', 'IDIOMA')),
  constraint formacao_colaborador_data_ck    check (dt_inicio is not null or dt_conclusao is not null),
  constraint formacao_colaborador_conc_ck    check (dt_conclusao is null or dt_inicio is null or dt_conclusao >= dt_inicio),
  constraint formacao_colaborador_valid_ck   check (dt_validade is null or dt_validade >= coalesce(dt_conclusao, dt_inicio)),
  constraint formacao_colaborador_carga_ck   check (nr_carga_horaria > 0),
  constraint formacao_colaborador_link_ck    check (ds_link is null or regexp_like(ds_link, '^https?://', 'i'))
);

create index if not exists formacao_colab_emp_colab_ix on formacao_colaborador (id_empresa, id_colaborador);
create index if not exists formacao_colab_colab_ix     on formacao_colaborador (id_colaborador);
create index if not exists formacao_colab_validade_ix  on formacao_colaborador (id_empresa, tp_formacao, dt_validade);

comment on table  formacao_colaborador                  is 'Formações acadêmicas, cursos, idiomas e certificações do colaborador.';
comment on column formacao_colaborador.id_formacao      is 'PK (identity).';
comment on column formacao_colaborador.id_empresa       is 'Empresa (tenant). Sempre igual à empresa do colaborador.';
comment on column formacao_colaborador.id_colaborador   is 'Colaborador (FK para COLABORADOR).';
comment on column formacao_colaborador.tp_formacao      is 'GRADUACAO, POS, MBA, CURSO, CERTIFICACAO ou IDIOMA.';
comment on column formacao_colaborador.ds_instituicao   is 'Instituição de ensino ou entidade certificadora.';
comment on column formacao_colaborador.ds_titulo        is 'Nome do curso, título ou certificação.';
comment on column formacao_colaborador.dt_inicio        is 'Data de início.';
comment on column formacao_colaborador.dt_conclusao     is 'Data de conclusão (nula se em andamento).';
comment on column formacao_colaborador.dt_validade      is 'Validade, para certificações que expiram.';
comment on column formacao_colaborador.nr_carga_horaria is 'Carga horária em horas.';
comment on column formacao_colaborador.bl_anexo         is 'Anexo (diploma, certificado).';
comment on column formacao_colaborador.ds_mime_type     is 'MIME type do anexo.';
comment on column formacao_colaborador.ds_nome_arquivo  is 'Nome original do arquivo anexado.';
comment on column formacao_colaborador.ds_link          is 'Link externo de verificação (alternativa ao anexo).';
comment on column formacao_colaborador.dt_criacao       is 'Auditoria: data/hora de criação.';
comment on column formacao_colaborador.usr_criacao      is 'Auditoria: usuário que criou.';
comment on column formacao_colaborador.dt_alteracao     is 'Auditoria: data/hora da última alteração.';
comment on column formacao_colaborador.usr_alteracao    is 'Auditoria: usuário da última alteração.';


--------------------------------------------------------------------------------
-- 4b. SOLICITACAO_CORRECAO · pedido do colaborador para o RH revisar o histórico
--------------------------------------------------------------------------------
create table if not exists solicitacao_correcao (
  id_solicitacao          number generated always as identity,
  id_empresa              number         not null,
  id_colaborador          number         not null,
  id_historico_carreira   number,
  ds_mensagem             varchar2(2000) not null,
  st_solicitacao          varchar2(10)   default 'ABERTA' not null,
  ds_resposta             varchar2(2000),
  dt_resolucao            timestamp with time zone,
  usr_resolucao           varchar2(255),
  dt_criacao              timestamp with time zone default systimestamp not null,
  usr_criacao             varchar2(255) default coalesce(sys_context('APEX$SESSION', 'APP_USER'), sys_context('USERENV', 'SESSION_USER')) not null,
  dt_alteracao            timestamp with time zone,
  usr_alteracao           varchar2(255),
  constraint solicitacao_correcao_pk         primary key (id_solicitacao),
  constraint solicitacao_correcao_empresa_fk foreign key (id_empresa)            references empresa (id_empresa),
  constraint solicitacao_correcao_colab_fk   foreign key (id_colaborador)        references colaborador (id_colaborador),
  constraint solicitacao_correcao_hist_fk    foreign key (id_historico_carreira) references historico_carreira (id_historico_carreira),
  constraint solicitacao_correcao_st_ck      check (st_solicitacao in ('ABERTA', 'RESOLVIDA', 'RECUSADA')),
  constraint solicitacao_correcao_res_ck     check (st_solicitacao = 'ABERTA' or dt_resolucao is not null)
);

create index if not exists solicitacao_corr_emp_st_ix on solicitacao_correcao (id_empresa, st_solicitacao);
create index if not exists solicitacao_corr_colab_ix  on solicitacao_correcao (id_colaborador);
create index if not exists solicitacao_corr_hist_ix   on solicitacao_correcao (id_historico_carreira);

comment on table  solicitacao_correcao                       is 'Pedidos do colaborador para o RH revisar o próprio histórico. A correção em si é feita por estorno + novo lançamento.';
comment on column solicitacao_correcao.id_solicitacao        is 'PK (identity).';
comment on column solicitacao_correcao.id_empresa            is 'Empresa (tenant) do colaborador.';
comment on column solicitacao_correcao.id_colaborador        is 'Colaborador que pediu a correção (sempre o próprio usuário).';
comment on column solicitacao_correcao.id_historico_carreira is 'Lançamento questionado (opcional).';
comment on column solicitacao_correcao.ds_mensagem           is 'O que está incorreto, nas palavras do colaborador.';
comment on column solicitacao_correcao.st_solicitacao        is 'ABERTA, RESOLVIDA ou RECUSADA.';
comment on column solicitacao_correcao.ds_resposta           is 'Resposta do RH.';
comment on column solicitacao_correcao.dt_resolucao          is 'Data/hora em que o RH respondeu.';
comment on column solicitacao_correcao.usr_resolucao         is 'Usuário do RH que respondeu.';
comment on column solicitacao_correcao.dt_criacao            is 'Auditoria: data/hora de criação.';
comment on column solicitacao_correcao.usr_criacao           is 'Auditoria: usuário que criou.';
comment on column solicitacao_correcao.dt_alteracao          is 'Auditoria: data/hora da última alteração.';
comment on column solicitacao_correcao.usr_alteracao         is 'Auditoria: usuário da última alteração.';


--------------------------------------------------------------------------------
-- 5. LOG_ACESSO_SALARIAL · LGPD: quem viu dados salariais, quando e onde
--------------------------------------------------------------------------------
create table if not exists log_acesso_salarial (
  id_log_acesso   number generated always as identity,
  id_empresa      number        not null,
  id_colaborador  number        not null,
  ds_contexto     varchar2(400),
  nr_aplicacao    number,
  nr_pagina       number,
  ds_ip           varchar2(100),
  dt_criacao      timestamp with time zone default systimestamp not null,
  usr_criacao     varchar2(255) default coalesce(sys_context('APEX$SESSION', 'APP_USER'), sys_context('USERENV', 'SESSION_USER')) not null,
  constraint log_acesso_salarial_pk         primary key (id_log_acesso),
  constraint log_acesso_salarial_empresa_fk foreign key (id_empresa)     references empresa (id_empresa),
  constraint log_acesso_salarial_colab_fk   foreign key (id_colaborador) references colaborador (id_colaborador)
);

create index if not exists log_acesso_sal_emp_colab_ix on log_acesso_salarial (id_empresa, id_colaborador);
create index if not exists log_acesso_sal_colab_ix     on log_acesso_salarial (id_colaborador);
create index if not exists log_acesso_sal_dt_ix        on log_acesso_salarial (id_empresa, dt_criacao);

comment on table  log_acesso_salarial                is 'LGPD: registro de cada acesso a dados salariais do histórico de carreira. Somente inserção.';
comment on column log_acesso_salarial.id_log_acesso  is 'PK (identity).';
comment on column log_acesso_salarial.id_empresa     is 'Empresa (tenant) do colaborador consultado.';
comment on column log_acesso_salarial.id_colaborador is 'Colaborador cujos dados salariais foram exibidos.';
comment on column log_acesso_salarial.ds_contexto    is 'Onde o dado foi exibido (página, região, lançamento).';
comment on column log_acesso_salarial.nr_aplicacao   is 'ID da aplicação APEX.';
comment on column log_acesso_salarial.nr_pagina      is 'Número da página APEX.';
comment on column log_acesso_salarial.ds_ip          is 'IP de origem informado pelo ORDS (quando disponível).';
comment on column log_acesso_salarial.dt_criacao     is 'Data/hora do acesso.';
comment on column log_acesso_salarial.usr_criacao    is 'Usuário que acessou.';


--------------------------------------------------------------------------------
-- 6. LOG_AUDITORIA_CARREIRA · trilha de todas as operações (preenchida por trigger)
--------------------------------------------------------------------------------
create table if not exists log_auditoria_carreira (
  id_log_auditoria number generated always as identity,
  id_empresa       number        not null,
  nm_tabela        varchar2(128) not null,
  id_registro      number        not null,
  tp_operacao      varchar2(1)   not null,
  st_anterior      varchar2(10),
  st_novo          varchar2(10),
  dt_criacao       timestamp with time zone default systimestamp not null,
  usr_criacao      varchar2(255) default coalesce(sys_context('APEX$SESSION', 'APP_USER'), sys_context('USERENV', 'SESSION_USER')) not null,
  constraint log_auditoria_carreira_pk         primary key (id_log_auditoria),
  constraint log_auditoria_carreira_empresa_fk foreign key (id_empresa) references empresa (id_empresa),
  constraint log_auditoria_carreira_op_ck      check (tp_operacao in ('I', 'U', 'D'))
);

create index if not exists log_auditoria_carr_reg_ix on log_auditoria_carreira (nm_tabela, id_registro);
create index if not exists log_auditoria_carr_emp_ix on log_auditoria_carreira (id_empresa, dt_criacao);

comment on table  log_auditoria_carreira             is 'Trilha de auditoria das tabelas do módulo (inserções, alterações e exclusões). Somente inserção.';
comment on column log_auditoria_carreira.id_log_auditoria is 'PK (identity).';
comment on column log_auditoria_carreira.id_empresa  is 'Empresa (tenant) do registro auditado.';
comment on column log_auditoria_carreira.nm_tabela   is 'Tabela auditada.';
comment on column log_auditoria_carreira.id_registro is 'PK do registro auditado.';
comment on column log_auditoria_carreira.tp_operacao is 'I = inserção, U = alteração, D = exclusão.';
comment on column log_auditoria_carreira.st_anterior is 'Status antes da operação (HISTORICO_CARREIRA).';
comment on column log_auditoria_carreira.st_novo     is 'Status depois da operação (HISTORICO_CARREIRA).';
comment on column log_auditoria_carreira.dt_criacao  is 'Data/hora da operação.';
comment on column log_auditoria_carreira.usr_criacao is 'Usuário que executou a operação.';
