  CREATE TABLE "APP_LOG" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"LOG_TS" TIMESTAMP (6) WITH TIME ZONE DEFAULT systimestamp NOT NULL ENABLE, 
	"NIVEL" VARCHAR2(10) NOT NULL ENABLE, 
	"APP_ID" NUMBER, 
	"PAGE_ID" NUMBER, 
	"APEX_USER" VARCHAR2(255), 
	"SESSION_ID" NUMBER, 
	"ORIGEM" VARCHAR2(255), 
	"MENSAGEM" VARCHAR2(4000), 
	"DETALHE" CLOB, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CANAL_MENSAGEM_ANEXO" 
   (	"ID_ANEXO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_CANAL_MENSAGEM" NUMBER NOT NULL ENABLE, 
	"NOME_ARQUIVO" VARCHAR2(400) NOT NULL ENABLE, 
	"MIME_TYPE" VARCHAR2(200), 
	"TAMANHO" NUMBER, 
	"CONTEUDO" BLOB NOT NULL ENABLE, 
	"DATA_UPLOAD" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_ANEXO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "COLABORADOR" 
   (	"ID_COLABORADOR" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_EMPRESA" NUMBER NOT NULL ENABLE, 
	"ID_DEPARTAMENTO" NUMBER NOT NULL ENABLE, 
	"ID_CARGO" NUMBER NOT NULL ENABLE, 
	"ID_GESTOR" NUMBER, 
	"NOME_COMPLETO" VARCHAR2(200) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(200) NOT NULL ENABLE, 
	"DATA_ADMISSAO" DATE DEFAULT SYSDATE, 
	"LOGIN_APEX" VARCHAR2(255), 
	"DATA_DE_NASCIMENTO" DATE, 
	"STATUS" BOOLEAN, 
	"PRIMEIRO_NOME" VARCHAR2(30), 
	"ULTIMO_NOME" VARCHAR2(30), 
	"FOTO_URL" VARCHAR2(500), 
	"IMAGEM_PERFIL" BLOB, 
	"MIME_TYPE" VARCHAR2(255), 
	"FILE_NAME" VARCHAR2(255), 
	"UPDATED" DATE, 
	"DESCRIPTION" VARCHAR2(255), 
	 PRIMARY KEY ("ID_COLABORADOR")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_COLABORADOR_EMAIL" UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "COMUNICADO" 
   (	"ID_COMUNICADO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_EMPRESA" NUMBER NOT NULL ENABLE, 
	"ID_AUTOR" NUMBER NOT NULL ENABLE, 
	"ID_DEPARTAMENTO" NUMBER, 
	"TITULO" VARCHAR2(200) NOT NULL ENABLE, 
	"CONTEUDO" CLOB, 
	"DATA_PUBLICACAO" DATE DEFAULT SYSDATE, 
	"IMAGEM" BLOB, 
	"MIME_TYPE" VARCHAR2(100), 
	"NOME_ARQUIVO" VARCHAR2(255), 
	 PRIMARY KEY ("ID_COMUNICADO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EMPRESA" 
   (	"ID_EMPRESA" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NOME" VARCHAR2(200) NOT NULL ENABLE, 
	"CNPJ" VARCHAR2(20) NOT NULL ENABLE, 
	"DATA_CRIACAO" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"NOME_FANTASIA" VARCHAR2(255) NOT NULL ENABLE, 
	"EMAIL_CORPORATIVO" VARCHAR2(255) NOT NULL ENABLE, 
	"TELEFONE" VARCHAR2(12) NOT NULL ENABLE, 
	"CEP" VARCHAR2(8) NOT NULL ENABLE, 
	"LOGRADOURO" VARCHAR2(100) NOT NULL ENABLE, 
	"NUMERO" VARCHAR2(4) NOT NULL ENABLE, 
	"COMPLEMENTO" VARCHAR2(30), 
	"BAIRRO" VARCHAR2(50) NOT NULL ENABLE, 
	"CIDADE" VARCHAR2(100) NOT NULL ENABLE, 
	"UF" VARCHAR2(2) NOT NULL ENABLE, 
	"STATUS" BOOLEAN NOT NULL ENABLE, 
	"LOGOTIPO_EMPRESA" BLOB, 
	 PRIMARY KEY ("ID_EMPRESA")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CANAL" 
   (	"ID_CANAL" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_EQUIPE" NUMBER, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(500), 
	"DATA_CRIACAO" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"STATUS" BOOLEAN DEFAULT TRUE NOT NULL ENABLE, 
	"TIPO" VARCHAR2(10) DEFAULT 'EQUIPE' NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_CANAL")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_CANAL_NOME_EQUIPE" UNIQUE ("ID_EQUIPE", "NOME")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CANAL_TIPO_CK" CHECK (tipo in ('EQUIPE','DIRETO')) ENABLE
   ) ;

  CREATE TABLE "CANAL_MENSAGEM" 
   (	"ID_CANAL_MENSAGEM" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_CANAL" NUMBER NOT NULL ENABLE, 
	"ID_COLABORADOR" NUMBER NOT NULL ENABLE, 
	"CORPO" VARCHAR2(4000) NOT NULL ENABLE, 
	"DATA_ENVIO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"EDITADA" BOOLEAN DEFAULT FALSE NOT NULL ENABLE, 
	"DATA_EDICAO" TIMESTAMP (6), 
	"EXCLUIDA" BOOLEAN DEFAULT FALSE NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_CANAL_MENSAGEM")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CANAL_PARTICIPANTE" 
   (	"ID_CANAL" NUMBER NOT NULL ENABLE, 
	"ID_COLABORADOR" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "CANAL_PART_PK" PRIMARY KEY ("ID_CANAL", "ID_COLABORADOR")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CARGO" 
   (	"ID_CARGO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_EMPRESA" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(150) NOT NULL ENABLE, 
	"NIVEL" VARCHAR2(50), 
	"ID_DEPARTAMENTO" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_CARGO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "COMUNICADO_LEITURA" 
   (	"ID_COMUNICADO_LEITURA" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_COMUNICADO" NUMBER NOT NULL ENABLE, 
	"ID_COLABORADOR" NUMBER NOT NULL ENABLE, 
	"DATA_LEITURA" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_COMUNICADO_LEITURA")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_COMLEITURA" UNIQUE ("ID_COMUNICADO", "ID_COLABORADOR")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DEPARTAMENTO" 
   (	"ID_DEPARTAMENTO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_EMPRESA" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(150) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_DEPARTAMENTO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EQUIPE" 
   (	"ID_EQUIPE" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_EMPRESA" NUMBER NOT NULL ENABLE, 
	"ID_DEPARTAMENTO" NUMBER, 
	"ID_CRIADOR" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(150) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(500), 
	"DATA_CRIACAO" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"STATUS" BOOLEAN DEFAULT TRUE NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_EQUIPE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EQUIPE_MEMBRO" 
   (	"ID_EQUIPE_MEMBRO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_EQUIPE" NUMBER NOT NULL ENABLE, 
	"ID_COLABORADOR" NUMBER NOT NULL ENABLE, 
	"PAPEL" VARCHAR2(10) DEFAULT 'MEMBRO' NOT NULL ENABLE, 
	"DATA_ENTRADA" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CHECK (PAPEL IN ('ADMIN','MEMBRO')) ENABLE, 
	 PRIMARY KEY ("ID_EQUIPE_MEMBRO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_EQUIPE_MEMBRO" UNIQUE ("ID_EQUIPE", "ID_COLABORADOR")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "HTMLDB_PLAN_TABLE" 
   (	"STATEMENT_ID" VARCHAR2(30), 
	"PLAN_ID" NUMBER, 
	"TIMESTAMP" DATE, 
	"REMARKS" VARCHAR2(4000), 
	"OPERATION" VARCHAR2(30), 
	"OPTIONS" VARCHAR2(255), 
	"OBJECT_NODE" VARCHAR2(128), 
	"OBJECT_OWNER" VARCHAR2(128), 
	"OBJECT_NAME" VARCHAR2(128), 
	"OBJECT_ALIAS" VARCHAR2(261), 
	"OBJECT_INSTANCE" NUMBER(*,0), 
	"OBJECT_TYPE" VARCHAR2(128), 
	"OPTIMIZER" VARCHAR2(255), 
	"SEARCH_COLUMNS" NUMBER, 
	"ID" NUMBER(*,0), 
	"PARENT_ID" NUMBER(*,0), 
	"DEPTH" NUMBER(*,0), 
	"POSITION" NUMBER(*,0), 
	"COST" NUMBER(*,0), 
	"CARDINALITY" NUMBER(*,0), 
	"BYTES" NUMBER(*,0), 
	"OTHER_TAG" VARCHAR2(255), 
	"PARTITION_START" VARCHAR2(255), 
	"PARTITION_STOP" VARCHAR2(255), 
	"PARTITION_ID" NUMBER(*,0), 
	"OTHER" LONG, 
	"DISTRIBUTION" VARCHAR2(30), 
	"CPU_COST" NUMBER(*,0), 
	"IO_COST" NUMBER(*,0), 
	"TEMP_SPACE" NUMBER(*,0), 
	"ACCESS_PREDICATES" VARCHAR2(4000), 
	"FILTER_PREDICATES" VARCHAR2(4000), 
	"PROJECTION" VARCHAR2(4000), 
	"TIME" NUMBER(*,0), 
	"QBLOCK_NAME" VARCHAR2(128)
   ) ;

  CREATE TABLE "MOVIMENTACAO_CARREIRA" 
   (	"ID_MOVIMENTACAO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_COLABORADOR" NUMBER NOT NULL ENABLE, 
	"ID_CARGO_ANTERIOR" NUMBER, 
	"ID_CARGO_NOVO" NUMBER NOT NULL ENABLE, 
	"TIPO" VARCHAR2(30) NOT NULL ENABLE, 
	"DATA_MOVIMENTACAO" DATE DEFAULT SYSDATE, 
	 CHECK (tipo IN ('PROMOCAO', 'TRANSFERENCIA', 
                                             'MUDANCA_SALARIAL', 'ADMISSAO')) ENABLE, 
	 PRIMARY KEY ("ID_MOVIMENTACAO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PRESENCA_COLABORADOR" 
   (	"ID_COLABORADOR" NUMBER NOT NULL ENABLE, 
	"STATUS_PRESENCA" VARCHAR2(10) DEFAULT 'OFFLINE' NOT NULL ENABLE, 
	"DATA_ULTIMO_PING" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CHECK (STATUS_PRESENCA IN ('ONLINE','AUSENTE','OFFLINE')) ENABLE, 
	 PRIMARY KEY ("ID_COLABORADOR")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CANAL" ADD CONSTRAINT "FK_CANAL_EQUIPE" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "EQUIPE" ("ID_EQUIPE") ON DELETE CASCADE ENABLE;

  ALTER TABLE "CANAL_MENSAGEM" ADD CONSTRAINT "FK_CANALMSG_CANAL" FOREIGN KEY ("ID_CANAL")
	  REFERENCES "CANAL" ("ID_CANAL") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CANAL_MENSAGEM" ADD CONSTRAINT "FK_CANALMSG_COLAB" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

  CREATE INDEX "IDX_CANALMSG_CANAL_DATA" ON "CANAL_MENSAGEM" ("ID_CANAL", "DATA_ENVIO") 
  ;

  ALTER TABLE "CANAL_MENSAGEM_ANEXO" ADD CONSTRAINT "FK_CANALANEXO_MSG" FOREIGN KEY ("ID_CANAL_MENSAGEM")
	  REFERENCES "CANAL_MENSAGEM" ("ID_CANAL_MENSAGEM") ON DELETE CASCADE ENABLE;

  ALTER TABLE "CANAL_PARTICIPANTE" ADD CONSTRAINT "CANAL_PART_FK1" FOREIGN KEY ("ID_CANAL")
	  REFERENCES "CANAL" ("ID_CANAL") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CANAL_PARTICIPANTE" ADD CONSTRAINT "CANAL_PART_FK2" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

  CREATE INDEX "CANAL_PART_COLAB_IX" ON "CANAL_PARTICIPANTE" ("ID_COLABORADOR", "ID_CANAL") 
  ;

  ALTER TABLE "CARGO" ADD CONSTRAINT "FK_CARGO_EMPRESA" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "EMPRESA" ("ID_EMPRESA") ENABLE;

  ALTER TABLE "COLABORADOR" ADD CONSTRAINT "FK_COLAB_EMPRESA" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "EMPRESA" ("ID_EMPRESA") ENABLE;
  ALTER TABLE "COLABORADOR" ADD CONSTRAINT "FK_COLAB_DEPARTAMENTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;
  ALTER TABLE "COLABORADOR" ADD CONSTRAINT "FK_COLAB_CARGO" FOREIGN KEY ("ID_CARGO")
	  REFERENCES "CARGO" ("ID_CARGO") ENABLE;
  ALTER TABLE "COLABORADOR" ADD CONSTRAINT "FK_COLAB_GESTOR" FOREIGN KEY ("ID_GESTOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") ENABLE;

  CREATE INDEX "IDX_COLAB_DEPARTAMENTO" ON "COLABORADOR" ("ID_DEPARTAMENTO") 
  ;

  CREATE INDEX "IDX_COLAB_GESTOR" ON "COLABORADOR" ("ID_GESTOR") 
  ;

  ALTER TABLE "COMUNICADO" ADD CONSTRAINT "FK_COM_EMPRESA" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "EMPRESA" ("ID_EMPRESA") ENABLE;
  ALTER TABLE "COMUNICADO" ADD CONSTRAINT "FK_COM_AUTOR" FOREIGN KEY ("ID_AUTOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;
  ALTER TABLE "COMUNICADO" ADD CONSTRAINT "FK_COM_DEPARTAMENTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;

  CREATE INDEX "IDX_COM_DEPARTAMENTO" ON "COMUNICADO" ("ID_DEPARTAMENTO") 
  ;

  ALTER TABLE "COMUNICADO_LEITURA" ADD CONSTRAINT "FK_COMLEITURA_COMUNICADO" FOREIGN KEY ("ID_COMUNICADO")
	  REFERENCES "COMUNICADO" ("ID_COMUNICADO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "COMUNICADO_LEITURA" ADD CONSTRAINT "FK_COMLEITURA_COLAB" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

  CREATE INDEX "IDX_COMLEITURA_COLAB" ON "COMUNICADO_LEITURA" ("ID_COLABORADOR") 
  ;

  ALTER TABLE "DEPARTAMENTO" ADD CONSTRAINT "FK_DEPARTAMENTO_EMPRESA" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "EMPRESA" ("ID_EMPRESA") ENABLE;

  ALTER TABLE "EQUIPE" ADD CONSTRAINT "FK_EQUIPE_EMPRESA" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "EMPRESA" ("ID_EMPRESA") ENABLE;
  ALTER TABLE "EQUIPE" ADD CONSTRAINT "FK_EQUIPE_DEPARTAMENTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;
  ALTER TABLE "EQUIPE" ADD CONSTRAINT "FK_EQUIPE_CRIADOR" FOREIGN KEY ("ID_CRIADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

  CREATE INDEX "IDX_EQUIPE_DEPARTAMENTO" ON "EQUIPE" ("ID_DEPARTAMENTO") 
  ;

  CREATE INDEX "IDX_EQUIPE_EMPRESA" ON "EQUIPE" ("ID_EMPRESA") 
  ;

  ALTER TABLE "EQUIPE_MEMBRO" ADD CONSTRAINT "FK_EQMEMBRO_EQUIPE" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "EQUIPE" ("ID_EQUIPE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "EQUIPE_MEMBRO" ADD CONSTRAINT "FK_EQMEMBRO_COLAB" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

  CREATE INDEX "IDX_EQMEMBRO_COLAB" ON "EQUIPE_MEMBRO" ("ID_COLABORADOR") 
  ;

  ALTER TABLE "MOVIMENTACAO_CARREIRA" ADD CONSTRAINT "FK_MOV_COLABORADOR" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;
  ALTER TABLE "MOVIMENTACAO_CARREIRA" ADD CONSTRAINT "FK_MOV_CARGO_ANTERIOR" FOREIGN KEY ("ID_CARGO_ANTERIOR")
	  REFERENCES "CARGO" ("ID_CARGO") ENABLE;
  ALTER TABLE "MOVIMENTACAO_CARREIRA" ADD CONSTRAINT "FK_MOV_CARGO_NOVO" FOREIGN KEY ("ID_CARGO_NOVO")
	  REFERENCES "CARGO" ("ID_CARGO") ENABLE;

  CREATE INDEX "IDX_MOV_COLABORADOR" ON "MOVIMENTACAO_CARREIRA" ("ID_COLABORADOR") 
  ;

  ALTER TABLE "PRESENCA_COLABORADOR" ADD CONSTRAINT "FK_PRESENCA_COLAB" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

   COMMENT ON TABLE "PRESENCA_COLABORADOR"  IS 'Atualizada via heartbeat do navegador (Dynamic Action Interval). Um job periódico marca OFFLINE quem não dá ping há mais de N minutos.';
create or replace function ch_get_canal_direto ( 
  p_colab_a in number, 
  p_colab_b in number 
) return number is 
  l_id_canal number; 
  l_menor    number := least(p_colab_a, p_colab_b); 
  l_maior    number := greatest(p_colab_a, p_colab_b); 
begin 
  select cp1.id_canal into l_id_canal 
  from   canal_participante cp1 
  join   canal_participante cp2 on cp2.id_canal = cp1.id_canal 
  join   canal c                on c.id_canal   = cp1.id_canal 
  where  cp1.id_colaborador = p_colab_a 
  and    cp2.id_colaborador = p_colab_b 
  and    c.tipo = 'DIRETO' 
  fetch first 1 row only; 
 
  return l_id_canal; 
exception 
  when no_data_found then 
    insert into canal (nome, tipo, data_criacao, status) 
    values ('DM-' || l_menor || '-' || l_maior, 'DIRETO', sysdate, true) 
    returning id_canal into l_id_canal; 
 
    insert into canal_participante (id_canal, id_colaborador) 
    select l_id_canal, p_colab_a from dual 
    union all 
    select l_id_canal, p_colab_b from dual; 
 
    return l_id_canal; 
end;
/





















































  CREATE INDEX "IDX_EQMEMBRO_COLAB" ON "EQUIPE_MEMBRO" ("ID_COLABORADOR") 
  ;

  CREATE INDEX "IDX_MOV_COLABORADOR" ON "MOVIMENTACAO_CARREIRA" ("ID_COLABORADOR") 
  ;

  CREATE INDEX "IDX_COLAB_DEPARTAMENTO" ON "COLABORADOR" ("ID_DEPARTAMENTO") 
  ;

  CREATE INDEX "IDX_COM_DEPARTAMENTO" ON "COMUNICADO" ("ID_DEPARTAMENTO") 
  ;

  CREATE UNIQUE INDEX "UQ_COMLEITURA" ON "COMUNICADO_LEITURA" ("ID_COMUNICADO", "ID_COLABORADOR") 
  ;

  CREATE UNIQUE INDEX "SYS_C0030673" ON "COLABORADOR" ("ID_COLABORADOR") 
  ;

  CREATE UNIQUE INDEX "SYS_C0036306" ON "CANAL_MENSAGEM" ("ID_CANAL_MENSAGEM") 
  ;

  CREATE UNIQUE INDEX "SYS_C0036326" ON "COMUNICADO_LEITURA" ("ID_COMUNICADO_LEITURA") 
  ;

  CREATE UNIQUE INDEX "SYS_C0036320" ON "PRESENCA_COLABORADOR" ("ID_COLABORADOR") 
  ;

  CREATE UNIQUE INDEX "UQ_CANAL_NOME_EQUIPE" ON "CANAL" ("ID_EQUIPE", "NOME") 
  ;

  CREATE UNIQUE INDEX "SYS_C0030684" ON "MOVIMENTACAO_CARREIRA" ("ID_MOVIMENTACAO") 
  ;

  CREATE UNIQUE INDEX "SYS_C0036655" ON "APP_LOG" ("ID") 
  ;

  CREATE INDEX "IDX_CANALMSG_CANAL_DATA" ON "CANAL_MENSAGEM" ("ID_CANAL", "DATA_ENVIO") 
  ;

  CREATE UNIQUE INDEX "SYS_C0030664" ON "CARGO" ("ID_CARGO") 
  ;

  CREATE UNIQUE INDEX "SYS_C0036287" ON "EQUIPE_MEMBRO" ("ID_EQUIPE_MEMBRO") 
  ;

  CREATE UNIQUE INDEX "SYS_C0036314" ON "CANAL_MENSAGEM_ANEXO" ("ID_ANEXO") 
  ;

  CREATE UNIQUE INDEX "UQ_EQUIPE_MEMBRO" ON "EQUIPE_MEMBRO" ("ID_EQUIPE", "ID_COLABORADOR") 
  ;

  CREATE UNIQUE INDEX "SYS_C0036277" ON "EQUIPE" ("ID_EQUIPE") 
  ;

  CREATE UNIQUE INDEX "CANAL_PART_PK" ON "CANAL_PARTICIPANTE" ("ID_CANAL", "ID_COLABORADOR") 
  ;

  CREATE UNIQUE INDEX "SYS_C0030659" ON "DEPARTAMENTO" ("ID_DEPARTAMENTO") 
  ;

  CREATE INDEX "CANAL_PART_COLAB_IX" ON "CANAL_PARTICIPANTE" ("ID_COLABORADOR", "ID_CANAL") 
  ;

  CREATE INDEX "APP_LOG_TS_IX" ON "APP_LOG" (SYS_EXTRACT_UTC("LOG_TS") DESC) 
  ;

  CREATE UNIQUE INDEX "SYS_C0030692" ON "COMUNICADO" ("ID_COMUNICADO") 
  ;

  CREATE INDEX "IDX_COMLEITURA_COLAB" ON "COMUNICADO_LEITURA" ("ID_COLABORADOR") 
  ;

  CREATE INDEX "IDX_EQUIPE_DEPARTAMENTO" ON "EQUIPE" ("ID_DEPARTAMENTO") 
  ;

  CREATE UNIQUE INDEX "UQ_COLABORADOR_EMAIL" ON "COLABORADOR" ("EMAIL") 
  ;

  CREATE INDEX "IDX_COLAB_GESTOR" ON "COLABORADOR" ("ID_GESTOR") 
  ;

  CREATE INDEX "IDX_EQUIPE_EMPRESA" ON "EQUIPE" ("ID_EMPRESA") 
  ;

  CREATE UNIQUE INDEX "SYS_C0030655" ON "EMPRESA" ("ID_EMPRESA") 
  ;

  CREATE UNIQUE INDEX "SYS_C0036296" ON "CANAL" ("ID_CANAL") 
  ;































create or replace package log_pkg as 
  procedure gravar(p_nivel varchar2, p_msg varchar2, p_origem varchar2 default null, p_detalhe clob default null); 
  procedure erro (p_msg varchar2, p_origem varchar2 default null); 
  procedure aviso(p_msg varchar2, p_origem varchar2 default null); 
  procedure info (p_msg varchar2, p_origem varchar2 default null); 
  function apex_error_handler(p_error in apex_error.t_error) return apex_error.t_error_result; 
end;
/
create or replace PACKAGE PKG_COMUNICADO AS 
 
    -- Cria um comunicado. ID_DEPARTAMENTO NULL = empresa toda. 
    FUNCTION CRIAR_COMUNICADO ( 
        p_id_empresa      IN NUMBER, 
        p_id_autor        IN NUMBER, 
        p_titulo          IN VARCHAR2, 
        p_conteudo        IN CLOB, 
        p_id_departamento IN NUMBER DEFAULT NULL, 
        p_imagem          IN BLOB DEFAULT NULL, 
        p_mime_type       IN VARCHAR2 DEFAULT NULL, 
        p_nome_arquivo    IN VARCHAR2 DEFAULT NULL 
    ) RETURN NUMBER; 
 
    -- Marca um comunicado como lido para o colaborador. Idempotente. 
    PROCEDURE MARCAR_COMO_LIDO ( 
        p_id_comunicado  IN NUMBER, 
        p_id_colaborador IN NUMBER 
    ); 
 
    -- Quantidade de comunicados elegíveis (empresa/depto) ainda não lidos. 
    FUNCTION QTD_NAO_LIDOS ( 
        p_id_colaborador IN NUMBER 
    ) RETURN NUMBER; 
 
END PKG_COMUNICADO;
/
create or replace PACKAGE PKG_EQUIPE_CANAL AS 
 
    -- Cria a equipe e já inclui o criador como ADMIN. 
    FUNCTION CRIAR_EQUIPE ( 
        p_id_empresa      IN NUMBER, 
        p_id_criador      IN NUMBER, 
        p_nome            IN VARCHAR2, 
        p_descricao       IN VARCHAR2 DEFAULT NULL, 
        p_id_departamento IN NUMBER DEFAULT NULL 
    ) RETURN NUMBER; 
 
    -- Adiciona um colaborador à equipe. Ignora silenciosamente se já for membro. 
    PROCEDURE ADICIONAR_MEMBRO ( 
        p_id_equipe      IN NUMBER, 
        p_id_colaborador IN NUMBER, 
        p_papel          IN VARCHAR2 DEFAULT 'MEMBRO' 
    ); 
 
    -- Remove um membro da equipe. Bloqueia se for o único ADMIN restante. 
    PROCEDURE REMOVER_MEMBRO ( 
        p_id_equipe_membro IN NUMBER 
    ); 
 
    -- Cria um canal dentro de uma equipe. 
    FUNCTION CRIAR_CANAL ( 
        p_id_equipe  IN NUMBER, 
        p_nome       IN VARCHAR2, 
        p_descricao  IN VARCHAR2 DEFAULT NULL 
    ) RETURN NUMBER; 
 
    -- Envia uma mensagem no canal. Valida que o colaborador é membro da equipe dona do canal. 
    FUNCTION ENVIAR_MENSAGEM_CANAL ( 
        p_id_canal       IN NUMBER, 
        p_id_colaborador IN NUMBER, 
        p_corpo          IN VARCHAR2 
    ) RETURN NUMBER; 
 
    -- Heartbeat de presença — chamado pelo polling do navegador. 
    PROCEDURE ATUALIZAR_PRESENCA ( 
        p_id_colaborador IN NUMBER, 
        p_status         IN VARCHAR2 DEFAULT 'ONLINE' 
    ); 
 
    -- Marca como OFFLINE quem não dá ping há mais de p_minutos_limite minutos. 
    -- Chamado por um job DBMS_SCHEDULER a cada 1-2 minutos. 
    PROCEDURE ATUALIZAR_OFFLINE ( 
        p_minutos_limite IN NUMBER DEFAULT 3 
    ); 
 
END PKG_EQUIPE_CANAL;
/
create or replace package "PKG_LOGS" as

end "PKG_LOGS";
/



















  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_CANAL_FEED" ("ID_CANAL_MENSAGEM", "ID_CANAL", "NOME_CANAL", "ID_EQUIPE", "ID_COLABORADOR", "NOME_AUTOR", "AUTOR_LOGIN", "CORPO", "DATA_ENVIO", "EDITADA", "EXCLUIDA", "STATUS_AUTOR", "QTD_ANEXOS") AS 
  SELECT 
    m."ID_CANAL_MENSAGEM", 
    m."ID_CANAL", 
    c."NOME"              AS NOME_CANAL, 
    c."ID_EQUIPE", 
    m."ID_COLABORADOR", 
    col."NOME_COMPLETO"   AS NOME_AUTOR, 
    col."LOGIN_APEX"      AS AUTOR_LOGIN, 
    m."CORPO", 
    m."DATA_ENVIO", 
    m."EDITADA", 
    m."EXCLUIDA", 
    NVL(p."STATUS_PRESENCA", 'OFFLINE') AS STATUS_AUTOR, 
    (SELECT COUNT(*) FROM "CANAL_MENSAGEM_ANEXO" a 
      WHERE a."ID_CANAL_MENSAGEM" = m."ID_CANAL_MENSAGEM") AS QTD_ANEXOS 
FROM "CANAL_MENSAGEM" m 
JOIN "CANAL"        c   ON c."ID_CANAL" = m."ID_CANAL" 
JOIN "COLABORADOR"  col ON col."ID_COLABORADOR" = m."ID_COLABORADOR" 
LEFT JOIN "PRESENCA_COLABORADOR" p ON p."ID_COLABORADOR" = col."ID_COLABORADOR" 
WHERE m."EXCLUIDA" = FALSE;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_MINHAS_EQUIPES" ("ID_COLABORADOR", "LOGIN_APEX", "ID_EQUIPE", "NOME_EQUIPE", "ID_EMPRESA", "PAPEL", "ID_CANAL", "NOME_CANAL") AS 
  SELECT 
    em."ID_COLABORADOR", 
    col."LOGIN_APEX", 
    e."ID_EQUIPE", 
    e."NOME"     AS NOME_EQUIPE, 
    e."ID_EMPRESA", 
    em."PAPEL", 
    c."ID_CANAL", 
    c."NOME"     AS NOME_CANAL 
FROM "EQUIPE_MEMBRO" em 
JOIN "COLABORADOR" col ON col."ID_COLABORADOR" = em."ID_COLABORADOR" 
JOIN "EQUIPE"       e  ON e."ID_EQUIPE" = em."ID_EQUIPE" AND e."STATUS" = TRUE 
LEFT JOIN "CANAL"    c ON c."ID_EQUIPE" = e."ID_EQUIPE" AND c."STATUS" = TRUE;

   COMMENT ON TABLE "PRESENCA_COLABORADOR"  IS 'Atualizada via heartbeat do navegador (Dynamic Action Interval). Um job periódico marca OFFLINE quem não dá ping há mais de N minutos.';































create or replace package body log_pkg as

  procedure gravar(p_nivel varchar2, p_msg varchar2, p_origem varchar2 default null, p_detalhe clob default null) is
    pragma autonomous_transaction;   -- grava mesmo se a transação principal der rollback
  begin
    insert into app_log (nivel, app_id, page_id, apex_user, session_id, origem, mensagem, detalhe)
    values (p_nivel, v('APP_ID'), v('APP_PAGE_ID'), v('APP_USER'), v('APP_SESSION'),
            substr(p_origem, 1, 255), substr(p_msg, 1, 4000), p_detalhe);
    commit;
  exception when others then
    rollback;                        -- log nunca pode derrubar a aplicação
    apex_debug.error('LOG_PKG.gravar falhou: %s', sqlerrm);
  end;

  procedure erro (p_msg varchar2, p_origem varchar2 default null) is begin gravar('ERRO',  p_msg, p_origem); end;
  procedure aviso(p_msg varchar2, p_origem varchar2 default null) is begin gravar('AVISO', p_msg, p_origem); end;
  procedure info (p_msg varchar2, p_origem varchar2 default null) is begin gravar('INFO',  p_msg, p_origem); end;

  -- Remove linhas internas do APEX/SYS, mantendo só o que aponta para o seu código
  function limpar_stack(p_stack varchar2) return varchar2 is
    l_linhas apex_t_varchar2;
    l_saida  varchar2(4000);
  begin
    if p_stack is null then return null; end if;
    l_linhas := apex_string.split(p_stack, chr(10));
    for i in 1 .. l_linhas.count loop
      if l_linhas(i) is not null
         and l_linhas(i) not like '%"APEX\_%' escape '\'
         and l_linhas(i) not like '%"SYS.%' then
        l_saida := substr(l_saida || trim(l_linhas(i)) || chr(10), 1, 4000);
      end if;
    end loop;
    return rtrim(l_saida, chr(10));
  end;

  function apex_error_handler(p_error in apex_error.t_error) return apex_error.t_error_result is
    l_result apex_error.t_error_result;
    l_origem varchar2(255);
  begin
    l_result := apex_error.init_error_result(p_error);

    l_origem := case p_error.component.type
                  when 'APEX_APPLICATION_PAGE_DA_ACTS'  then 'Dynamic Action'
                  when 'APEX_APPLICATION_PAGE_PROC'     then 'Processo'
                  when 'APEX_APPLICATION_PAGE_VAL'      then 'Validação'
                  when 'APEX_APPLICATION_PAGE_ITEMS'    then 'Item'
                  when 'APEX_APPLICATION_PAGE_REGIONS'  then 'Região'
                  when 'APEX_APPLICATION_PAGE_COMP'     then 'Computação'
                  when 'APEX_APPLICATION_PROCESSES'     then 'Processo de aplicação'
                  else p_error.component.type
                end
                || case when p_error.component.name is not null
                        then ' – ' || p_error.component.name end;

    gravar(
      p_nivel   => 'ERRO',
      p_msg     => p_error.message,
      p_origem  => l_origem,
      p_detalhe =>
           'Erro Oracle: ' || nvl(regexp_substr(p_error.ora_sqlerrm, 'ORA-\d+:[^' || chr(10) || ']*'), '(nenhum)')
        || chr(10) || chr(10)
        || 'Onde ocorreu:' || chr(10)
        || nvl(limpar_stack(p_error.error_backtrace), '(sem backtrace)')
        || case when p_error.error_statement is not null
                then chr(10) || chr(10) || 'Comando:' || chr(10) || p_error.error_statement end
    );
    return l_result;
  end;

end;
/
create or replace PACKAGE BODY PKG_COMUNICADO AS 
 
    FUNCTION CRIAR_COMUNICADO ( 
        p_id_empresa      IN NUMBER, 
        p_id_autor        IN NUMBER, 
        p_titulo          IN VARCHAR2, 
        p_conteudo        IN CLOB, 
        p_id_departamento IN NUMBER DEFAULT NULL, 
        p_imagem          IN BLOB DEFAULT NULL, 
        p_mime_type       IN VARCHAR2 DEFAULT NULL, 
        p_nome_arquivo    IN VARCHAR2 DEFAULT NULL 
    ) RETURN NUMBER 
    IS 
        v_id_comunicado NUMBER; 
    BEGIN 
        INSERT INTO COMUNICADO ( 
            ID_EMPRESA, ID_AUTOR, ID_DEPARTAMENTO, TITULO, CONTEUDO, 
            DATA_PUBLICACAO, IMAGEM, MIME_TYPE, NOME_ARQUIVO 
        ) VALUES ( 
            p_id_empresa, p_id_autor, p_id_departamento, p_titulo, p_conteudo, 
            SYSDATE, p_imagem, p_mime_type, p_nome_arquivo 
        ) 
        RETURNING ID_COMUNICADO INTO v_id_comunicado; 
 
        COMMIT; 
        RETURN v_id_comunicado; 
 
    EXCEPTION 
        WHEN OTHERS THEN 
            ROLLBACK; 
            RAISE; 
    END CRIAR_COMUNICADO; 
 
 
    PROCEDURE MARCAR_COMO_LIDO ( 
        p_id_comunicado  IN NUMBER, 
        p_id_colaborador IN NUMBER 
    ) 
    IS 
    BEGIN 
        -- MERGE em vez de UPDATE/INSERT separados: cobre "já lido" e "primeira leitura" 
        -- num único statement, sem risco de violar a UNIQUE em corrida de cliques duplos. 
        MERGE INTO COMUNICADO_LEITURA tgt 
        USING (SELECT p_id_comunicado AS ID_COMUNICADO, p_id_colaborador AS ID_COLABORADOR FROM DUAL) src 
        ON (tgt.ID_COMUNICADO = src.ID_COMUNICADO AND tgt.ID_COLABORADOR = src.ID_COLABORADOR) 
        WHEN NOT MATCHED THEN 
            INSERT (ID_COMUNICADO, ID_COLABORADOR, DATA_LEITURA) 
            VALUES (src.ID_COMUNICADO, src.ID_COLABORADOR, SYSTIMESTAMP); 
 
        COMMIT; 
    END MARCAR_COMO_LIDO; 
 
 
    FUNCTION QTD_NAO_LIDOS ( 
        p_id_colaborador IN NUMBER 
    ) RETURN NUMBER 
    IS 
        v_qtd NUMBER; 
    BEGIN 
        SELECT COUNT(*) 
          INTO v_qtd 
          FROM COMUNICADO c 
          JOIN COLABORADOR col ON col.ID_COLABORADOR = p_id_colaborador 
         WHERE c.ID_EMPRESA = col.ID_EMPRESA 
           AND (c.ID_DEPARTAMENTO IS NULL OR c.ID_DEPARTAMENTO = col.ID_DEPARTAMENTO) 
           AND NOT EXISTS ( 
                SELECT 1 FROM COMUNICADO_LEITURA l 
                 WHERE l.ID_COMUNICADO = c.ID_COMUNICADO 
                   AND l.ID_COLABORADOR = p_id_colaborador 
           ); 
 
        RETURN v_qtd; 
    END QTD_NAO_LIDOS; 
 
END PKG_COMUNICADO;
/
create or replace PACKAGE BODY PKG_EQUIPE_CANAL AS 
 
    FUNCTION CRIAR_EQUIPE ( 
        p_id_empresa      IN NUMBER, 
        p_id_criador      IN NUMBER, 
        p_nome            IN VARCHAR2, 
        p_descricao       IN VARCHAR2 DEFAULT NULL, 
        p_id_departamento IN NUMBER DEFAULT NULL 
    ) RETURN NUMBER 
    IS 
        v_id_equipe NUMBER; 
    BEGIN 
        INSERT INTO EQUIPE (ID_EMPRESA, ID_DEPARTAMENTO, ID_CRIADOR, NOME, DESCRICAO) 
        VALUES (p_id_empresa, p_id_departamento, p_id_criador, p_nome, p_descricao) 
        RETURNING ID_EQUIPE INTO v_id_equipe; 
 
        -- O criador entra automaticamente como ADMIN da equipe que criou. 
        INSERT INTO EQUIPE_MEMBRO (ID_EQUIPE, ID_COLABORADOR, PAPEL) 
        VALUES (v_id_equipe, p_id_criador, 'ADMIN'); 
 
        COMMIT; 
        RETURN v_id_equipe; 
 
    EXCEPTION 
        WHEN OTHERS THEN 
            ROLLBACK; 
            RAISE; 
    END CRIAR_EQUIPE; 
 
 
    PROCEDURE ADICIONAR_MEMBRO ( 
        p_id_equipe      IN NUMBER, 
        p_id_colaborador IN NUMBER, 
        p_papel          IN VARCHAR2 DEFAULT 'MEMBRO' 
    ) 
    IS 
    BEGIN 
        MERGE INTO EQUIPE_MEMBRO tgt 
        USING (SELECT p_id_equipe AS ID_EQUIPE, p_id_colaborador AS ID_COLABORADOR FROM DUAL) src 
        ON (tgt.ID_EQUIPE = src.ID_EQUIPE AND tgt.ID_COLABORADOR = src.ID_COLABORADOR) 
        WHEN NOT MATCHED THEN 
            INSERT (ID_EQUIPE, ID_COLABORADOR, PAPEL) 
            VALUES (src.ID_EQUIPE, src.ID_COLABORADOR, p_papel); 
 
        COMMIT; 
    END ADICIONAR_MEMBRO; 
 
 
    PROCEDURE REMOVER_MEMBRO ( 
        p_id_equipe_membro IN NUMBER 
    ) 
    IS 
        v_id_equipe    EQUIPE_MEMBRO.ID_EQUIPE%TYPE; 
        v_papel        EQUIPE_MEMBRO.PAPEL%TYPE; 
        v_qtd_admins   NUMBER; 
    BEGIN 
        SELECT ID_EQUIPE, PAPEL 
          INTO v_id_equipe, v_papel 
          FROM EQUIPE_MEMBRO 
         WHERE ID_EQUIPE_MEMBRO = p_id_equipe_membro; 
 
        IF v_papel = 'ADMIN' THEN 
            SELECT COUNT(*) 
              INTO v_qtd_admins 
              FROM EQUIPE_MEMBRO 
             WHERE ID_EQUIPE = v_id_equipe 
               AND PAPEL = 'ADMIN'; 
 
            IF v_qtd_admins <= 1 THEN 
                RAISE_APPLICATION_ERROR(-20011, 
                    'Não é possível remover o único administrador da equipe. Promova outro membro a ADMIN antes.'); 
            END IF; 
        END IF; 
 
        DELETE FROM EQUIPE_MEMBRO WHERE ID_EQUIPE_MEMBRO = p_id_equipe_membro; 
        COMMIT; 
 
    EXCEPTION 
        WHEN NO_DATA_FOUND THEN 
            RAISE_APPLICATION_ERROR(-20012, 'Membro não encontrado.'); 
        WHEN OTHERS THEN 
            ROLLBACK; 
            RAISE; 
    END REMOVER_MEMBRO; 
 
 
    FUNCTION CRIAR_CANAL ( 
        p_id_equipe  IN NUMBER, 
        p_nome       IN VARCHAR2, 
        p_descricao  IN VARCHAR2 DEFAULT NULL 
    ) RETURN NUMBER 
    IS 
        v_id_canal NUMBER; 
    BEGIN 
        INSERT INTO CANAL (ID_EQUIPE, NOME, DESCRICAO) 
        VALUES (p_id_equipe, p_nome, p_descricao) 
        RETURNING ID_CANAL INTO v_id_canal; 
 
        COMMIT; 
        RETURN v_id_canal; 
 
    EXCEPTION 
        WHEN OTHERS THEN 
            ROLLBACK; 
            RAISE; 
    END CRIAR_CANAL; 
 
 
    FUNCTION ENVIAR_MENSAGEM_CANAL ( 
        p_id_canal       IN NUMBER, 
        p_id_colaborador IN NUMBER, 
        p_corpo          IN VARCHAR2 
    ) RETURN NUMBER 
    IS 
        v_id_canal_mensagem NUMBER; 
        v_qtd_membro        NUMBER; 
    BEGIN 
        ----------------------------------------------------------------- 
        -- Validação: só quem é membro da equipe dona do canal pode postar. 
        -- Evita que alguém envie mensagem via chamada direta da function 
        -- num canal de equipe da qual não faz parte. 
        ----------------------------------------------------------------- 
        SELECT COUNT(*) 
          INTO v_qtd_membro 
          FROM CANAL c 
          JOIN EQUIPE_MEMBRO em ON em.ID_EQUIPE = c.ID_EQUIPE 
         WHERE c.ID_CANAL = p_id_canal 
           AND em.ID_COLABORADOR = p_id_colaborador; 
 
        IF v_qtd_membro = 0 THEN 
            RAISE_APPLICATION_ERROR(-20010, 
                'Colaborador não é membro da equipe deste canal.'); 
        END IF; 
 
        INSERT INTO CANAL_MENSAGEM (ID_CANAL, ID_COLABORADOR, CORPO) 
        VALUES (p_id_canal, p_id_colaborador, p_corpo) 
        RETURNING ID_CANAL_MENSAGEM INTO v_id_canal_mensagem; 
 
        -- Enviar mensagem também conta como "estar online agora". 
        ATUALIZAR_PRESENCA(p_id_colaborador, 'ONLINE'); 
 
        COMMIT; 
        RETURN v_id_canal_mensagem; 
 
    EXCEPTION 
        WHEN OTHERS THEN 
            ROLLBACK; 
            RAISE; 
    END ENVIAR_MENSAGEM_CANAL; 
 
 
    PROCEDURE ATUALIZAR_PRESENCA ( 
        p_id_colaborador IN NUMBER, 
        p_status         IN VARCHAR2 DEFAULT 'ONLINE' 
    ) 
    IS 
    BEGIN 
        MERGE INTO PRESENCA_COLABORADOR tgt 
        USING (SELECT p_id_colaborador AS ID_COLABORADOR FROM DUAL) src 
        ON (tgt.ID_COLABORADOR = src.ID_COLABORADOR) 
        WHEN MATCHED THEN 
            UPDATE SET STATUS_PRESENCA = p_status, DATA_ULTIMO_PING = SYSTIMESTAMP 
        WHEN NOT MATCHED THEN 
            INSERT (ID_COLABORADOR, STATUS_PRESENCA, DATA_ULTIMO_PING) 
            VALUES (p_id_colaborador, p_status, SYSTIMESTAMP); 
 
        COMMIT; 
    END ATUALIZAR_PRESENCA; 
 
 
    PROCEDURE ATUALIZAR_OFFLINE ( 
        p_minutos_limite IN NUMBER DEFAULT 3 
    ) 
    IS 
    BEGIN 
        UPDATE PRESENCA_COLABORADOR 
           SET STATUS_PRESENCA = 'OFFLINE' 
         WHERE STATUS_PRESENCA <> 'OFFLINE' 
           AND DATA_ULTIMO_PING < SYSTIMESTAMP - NUMTODSINTERVAL(p_minutos_limite, 'MINUTE'); 
 
        COMMIT; 
    END ATUALIZAR_OFFLINE; 
 
END PKG_EQUIPE_CANAL;
/


















