--------------------------------------------------------------------------------
-- Corlix Hub · Perfis de acesso · 02 · Departamentos, cargos e papéis (empresa 1)
--
-- 1. Renomeia o departamento 20 ("Diretor de Recursos Humanos (CHRO)" é nome
--    de cargo) para "Diretoria de Recursos Humanos".
-- 2. Ajusta as identities de DEPARTAMENTO, CARGO e COLABORADOR para continuarem
--    depois do maior ID (os dados foram carregados com IDs manuais).
-- 3. Cria os cargos sugeridos em cada departamento (sem duplicar pelo nome).
-- 4. Vincula cada cargo aos papéis do APEX em CARGO_PAPEL.
--
-- Reexecutável: não apaga nada e não duplica cargos nem vínculos.
-- Papéis (Static ID no APEX):
--   gestor | diretoria | admin-rh | publicador-de-conteúdo
--   ("colaborador" é dado a todos pelo package; não entra aqui)
--------------------------------------------------------------------------------

alter table departamento modify id_departamento generated by default as identity (start with limit value);
alter table cargo        modify id_cargo        generated by default as identity (start with limit value);
alter table colaborador  modify id_colaborador  generated by default as identity (start with limit value);

declare
  c_empresa    constant number := 1;
  c_gestor     constant varchar2(100) := 'gestor';
  c_diretoria  constant varchar2(100) := 'diretoria';
  c_admin_rh   constant varchar2(100) := 'admin-rh';
  c_publicador constant varchar2(100) := unistr('publicador-de-conte\00FAdo');

  l_cargos_novos   pls_integer := 0;
  l_vinculos_novos pls_integer := 0;

  -- Garante que o departamento existe e é da empresa esperada.
  procedure conferir_departamento (p_id in number) is
    l_qt pls_integer;
  begin
    select count(*) into l_qt
      from departamento
     where id_departamento = p_id
       and id_empresa      = c_empresa;
    if l_qt = 0 then
      raise_application_error(-20100,
        'Departamento ' || p_id || ' não encontrado na empresa ' || c_empresa || '.');
    end if;
  end conferir_departamento;

  procedure vincular (p_id_cargo in number, p_papel in varchar2) is
  begin
    merge into cargo_papel t
    using (select p_id_cargo as id_cargo, p_papel as cd_papel from dual) s
       on (t.id_cargo = s.id_cargo and t.cd_papel = s.cd_papel)
     when not matched then
       insert (id_cargo, cd_papel) values (s.id_cargo, s.cd_papel);
    l_vinculos_novos := l_vinculos_novos + sql%rowcount;
  end vincular;

  -- Cria o cargo se ainda não existir (mesmo nome, sem diferenciar maiúsculas)
  -- e vincula os papéis informados.
  procedure cargo (
    p_id_departamento in number,
    p_nome            in varchar2,
    p_papeis          in apex_t_varchar2 default apex_t_varchar2()
  ) is
    l_id_cargo number;
  begin
    begin
      select id_cargo into l_id_cargo
        from cargo
       where id_empresa      = c_empresa
         and id_departamento = p_id_departamento
         and upper(trim(nome)) = upper(trim(p_nome))
       fetch first 1 row only;
    exception
      when no_data_found then
        insert into cargo (id_empresa, id_departamento, nome)
        values (c_empresa, p_id_departamento, p_nome)
        returning id_cargo into l_id_cargo;
        l_cargos_novos := l_cargos_novos + 1;
    end;

    for i in 1 .. p_papeis.count loop
      vincular(l_id_cargo, p_papeis(i));
    end loop;
  end cargo;

begin
  for d in (select column_value as id from table(apex_t_number(10, 20, 30, 40, 50, 60))) loop
    conferir_departamento(d.id);
  end loop;

  update departamento
     set nome = 'Diretoria de Recursos Humanos'
   where id_departamento = 20
     and id_empresa      = c_empresa
     and nome           <> 'Diretoria de Recursos Humanos';

  -- 10 · Presidência
  cargo(10, 'Presidente (CEO)',        apex_t_varchar2(c_gestor, c_diretoria, c_publicador));
  cargo(10, 'Chefe de Gabinete',       apex_t_varchar2(c_gestor));
  cargo(10, 'Assistente Executivo(a)');

  -- 20 · Diretoria de Recursos Humanos
  cargo(20, 'Diretor(a) de RH (CHRO)',                apex_t_varchar2(c_gestor, c_diretoria, c_admin_rh, c_publicador));
  cargo(20, 'Gerente de RH',                          apex_t_varchar2(c_gestor, c_admin_rh, c_publicador));
  cargo(20, 'Coordenador(a) de Departamento Pessoal', apex_t_varchar2(c_gestor, c_admin_rh, c_publicador));
  cargo(20, 'Analista de RH',                         apex_t_varchar2(c_admin_rh, c_publicador));
  cargo(20, 'Analista de Departamento Pessoal',       apex_t_varchar2(c_admin_rh, c_publicador));
  cargo(20, 'Assistente de RH');

  -- 30 · Diretoria Financeira e Administrativa
  cargo(30, 'Diretor(a) Financeiro(a) (CFO)',  apex_t_varchar2(c_gestor, c_diretoria, c_publicador));
  cargo(30, 'Gerente Financeiro(a)',           apex_t_varchar2(c_gestor));
  cargo(30, 'Coordenador(a) Administrativo(a)', apex_t_varchar2(c_gestor));
  cargo(30, 'Analista Financeiro(a)');
  cargo(30, 'Analista Contábil');
  cargo(30, 'Assistente Administrativo(a)');

  -- 40 · Diretoria Comercial e de Marketing
  cargo(40, 'Diretor(a) Comercial (CCO)',       apex_t_varchar2(c_gestor, c_diretoria, c_publicador));
  cargo(40, 'Gerente Comercial',                apex_t_varchar2(c_gestor));
  cargo(40, 'Gerente de Marketing',             apex_t_varchar2(c_gestor));
  cargo(40, 'Executivo(a) de Vendas');
  cargo(40, 'Analista de Marketing');
  cargo(40, 'Analista de Comunicação Interna',  apex_t_varchar2(c_publicador));

  -- 50 · Diretoria de Operações
  cargo(50, 'Diretor(a) de Operações (COO)',  apex_t_varchar2(c_gestor, c_diretoria, c_publicador));
  cargo(50, 'Gerente de Operações',           apex_t_varchar2(c_gestor));
  cargo(50, 'Supervisor(a) de Atendimento',   apex_t_varchar2(c_gestor));
  cargo(50, 'Analista de Operações');
  cargo(50, 'Assistente de Operações');

  -- 60 · Diretoria de Tecnologia e Informação
  cargo(60, 'Diretor(a) de Tecnologia (CTO)', apex_t_varchar2(c_gestor, c_diretoria, c_publicador));
  cargo(60, 'Gerente de TI',                  apex_t_varchar2(c_gestor));
  cargo(60, 'Tech Lead',                      apex_t_varchar2(c_gestor));
  cargo(60, 'Desenvolvedor(a)');
  cargo(60, 'Analista de Suporte');
  cargo(60, 'Administrador(a) de Sistemas');

  -- Cargos antigos chamados "Gestor" continuam aparecendo como gestor na P14.
  for g in (select id_cargo from cargo where id_empresa = c_empresa and upper(trim(nome)) = 'GESTOR') loop
    vincular(g.id_cargo, c_gestor);
  end loop;

  commit;

  dbms_output.put_line('Cargos criados: ' || l_cargos_novos || ' | vínculos cargo-papel criados: ' || l_vinculos_novos);

  -- Cargos da empresa sem papel extra: só recebem "colaborador". Revise a lista.
  for r in (
    select d.nome as departamento, c.nome as cargo
      from cargo c
      join departamento d on d.id_departamento = c.id_departamento
     where c.id_empresa = c_empresa
       and not exists (select 1 from cargo_papel p where p.id_cargo = c.id_cargo)
     order by d.nome, c.nome
  ) loop
    dbms_output.put_line('  só colaborador: ' || r.departamento || ' / ' || r.cargo);
  end loop;
end;
/
