
  ALTER TABLE "CANAL" ADD CONSTRAINT "FK_CANAL_EQUIPE" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "EQUIPE" ("ID_EQUIPE") ON DELETE CASCADE ENABLE;

  ALTER TABLE "CANAL_MENSAGEM" ADD CONSTRAINT "FK_CANALMSG_CANAL" FOREIGN KEY ("ID_CANAL")
	  REFERENCES "CANAL" ("ID_CANAL") ON DELETE CASCADE ENABLE;

  ALTER TABLE "CANAL_MENSAGEM" ADD CONSTRAINT "FK_CANALMSG_COLAB" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

  ALTER TABLE "CANAL_MENSAGEM_ANEXO" ADD CONSTRAINT "FK_CANALANEXO_MSG" FOREIGN KEY ("ID_CANAL_MENSAGEM")
	  REFERENCES "CANAL_MENSAGEM" ("ID_CANAL_MENSAGEM") ON DELETE CASCADE ENABLE;

  ALTER TABLE "CANAL_PARTICIPANTE" ADD CONSTRAINT "CANAL_PART_FK1" FOREIGN KEY ("ID_CANAL")
	  REFERENCES "CANAL" ("ID_CANAL") ON DELETE CASCADE ENABLE;

  ALTER TABLE "CANAL_PARTICIPANTE" ADD CONSTRAINT "CANAL_PART_FK2" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

  ALTER TABLE "CARGO" ADD CONSTRAINT "FK_CARGO_EMPRESA" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "EMPRESA" ("ID_EMPRESA") ENABLE;

  ALTER TABLE "CARGO_PAPEL" ADD CONSTRAINT "FK_CARGO_PAPEL_CARGO" FOREIGN KEY ("ID_CARGO")
	  REFERENCES "CARGO" ("ID_CARGO") ON DELETE CASCADE ENABLE;

  ALTER TABLE "COLABORADOR" ADD CONSTRAINT "FK_COLAB_CARGO" FOREIGN KEY ("ID_CARGO")
	  REFERENCES "CARGO" ("ID_CARGO") ENABLE;

  ALTER TABLE "COLABORADOR" ADD CONSTRAINT "FK_COLAB_DEPARTAMENTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;

  ALTER TABLE "COLABORADOR" ADD CONSTRAINT "FK_COLAB_EMPRESA" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "EMPRESA" ("ID_EMPRESA") ENABLE;

  ALTER TABLE "COLABORADOR" ADD CONSTRAINT "FK_COLAB_GESTOR" FOREIGN KEY ("ID_GESTOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") ENABLE;

  ALTER TABLE "COMUNICADO" ADD CONSTRAINT "FK_COM_AUTOR" FOREIGN KEY ("ID_AUTOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

  ALTER TABLE "COMUNICADO" ADD CONSTRAINT "FK_COM_DEPARTAMENTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;

  ALTER TABLE "COMUNICADO" ADD CONSTRAINT "FK_COM_EMPRESA" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "EMPRESA" ("ID_EMPRESA") ENABLE;

  ALTER TABLE "COMUNICADO_LEITURA" ADD CONSTRAINT "FK_COMLEITURA_COLAB" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

  ALTER TABLE "COMUNICADO_LEITURA" ADD CONSTRAINT "FK_COMLEITURA_COMUNICADO" FOREIGN KEY ("ID_COMUNICADO")
	  REFERENCES "COMUNICADO" ("ID_COMUNICADO") ON DELETE CASCADE ENABLE;

  ALTER TABLE "DEPARTAMENTO" ADD CONSTRAINT "FK_DEPARTAMENTO_EMPRESA" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "EMPRESA" ("ID_EMPRESA") ENABLE;

  ALTER TABLE "EQUIPE" ADD CONSTRAINT "FK_EQUIPE_CRIADOR" FOREIGN KEY ("ID_CRIADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

  ALTER TABLE "EQUIPE" ADD CONSTRAINT "FK_EQUIPE_DEPARTAMENTO" FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;

  ALTER TABLE "EQUIPE" ADD CONSTRAINT "FK_EQUIPE_EMPRESA" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "EMPRESA" ("ID_EMPRESA") ENABLE;

  ALTER TABLE "EQUIPE_MEMBRO" ADD CONSTRAINT "FK_EQMEMBRO_COLAB" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

  ALTER TABLE "EQUIPE_MEMBRO" ADD CONSTRAINT "FK_EQMEMBRO_EQUIPE" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "EQUIPE" ("ID_EQUIPE") ON DELETE CASCADE ENABLE;

  ALTER TABLE "MOVIMENTACAO_CARREIRA" ADD CONSTRAINT "FK_MOV_CARGO_ANTERIOR" FOREIGN KEY ("ID_CARGO_ANTERIOR")
	  REFERENCES "CARGO" ("ID_CARGO") ENABLE;

  ALTER TABLE "MOVIMENTACAO_CARREIRA" ADD CONSTRAINT "FK_MOV_CARGO_NOVO" FOREIGN KEY ("ID_CARGO_NOVO")
	  REFERENCES "CARGO" ("ID_CARGO") ENABLE;

  ALTER TABLE "MOVIMENTACAO_CARREIRA" ADD CONSTRAINT "FK_MOV_COLABORADOR" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;

  ALTER TABLE "PRESENCA_COLABORADOR" ADD CONSTRAINT "FK_PRESENCA_COLAB" FOREIGN KEY ("ID_COLABORADOR")
	  REFERENCES "COLABORADOR" ("ID_COLABORADOR") DISABLE;
