
  CREATE INDEX "APP_LOG_TS_IX" ON "APP_LOG" (SYS_EXTRACT_UTC("LOG_TS") DESC)
  ;

  CREATE INDEX "IDX_CANALMSG_CANAL_DATA" ON "CANAL_MENSAGEM" ("ID_CANAL", "DATA_ENVIO")
  ;

  CREATE INDEX "CANAL_PART_COLAB_IX" ON "CANAL_PARTICIPANTE" ("ID_COLABORADOR", "ID_CANAL")
  ;

  CREATE INDEX "IDX_CARGO_PAPEL_PAPEL" ON "CARGO_PAPEL" ("CD_PAPEL")
  ;

  CREATE INDEX "IDX_COLAB_DEPARTAMENTO" ON "COLABORADOR" ("ID_DEPARTAMENTO")
  ;

  CREATE INDEX "IDX_COLAB_GESTOR" ON "COLABORADOR" ("ID_GESTOR")
  ;

  CREATE INDEX "IDX_COM_DEPARTAMENTO" ON "COMUNICADO" ("ID_DEPARTAMENTO")
  ;

  CREATE INDEX "IDX_COMLEITURA_COLAB" ON "COMUNICADO_LEITURA" ("ID_COLABORADOR")
  ;

  CREATE INDEX "IDX_EQUIPE_DEPARTAMENTO" ON "EQUIPE" ("ID_DEPARTAMENTO")
  ;

  CREATE INDEX "IDX_EQUIPE_EMPRESA" ON "EQUIPE" ("ID_EMPRESA")
  ;

  CREATE INDEX "IDX_EQMEMBRO_COLAB" ON "EQUIPE_MEMBRO" ("ID_COLABORADOR")
  ;

  CREATE INDEX "IDX_MOV_COLABORADOR" ON "MOVIMENTACAO_CARREIRA" ("ID_COLABORADOR")
  ;
