
  CREATE INDEX "APP_LOG_TS_IX" ON "APP_LOG" (SYS_EXTRACT_UTC("LOG_TS") DESC)
  ;

  CREATE INDEX "IDX_CANALMSG_CANAL_DATA" ON "CANAL_MENSAGEM" ("ID_CANAL", "DATA_ENVIO")
  ;

  CREATE INDEX "CANAL_PART_COLAB_IX" ON "CANAL_PARTICIPANTE" ("ID_COLABORADOR", "ID_CANAL")
  ;

  CREATE INDEX "IDX_CARGO_PAPEL_PAPEL" ON "CARGO_PAPEL" ("CD_PAPEL")
  ;

  CREATE INDEX "IDX_COLAB_DEPARTAMENTO" ON "COLABORADOR" ("ID_DEPARTAMENTO")
  ;

  CREATE INDEX "IDX_COLAB_GESTOR" ON "COLABORADOR" ("ID_GESTOR")
  ;

  CREATE INDEX "IDX_COM_DEPARTAMENTO" ON "COMUNICADO" ("ID_DEPARTAMENTO")
  ;

  CREATE INDEX "IDX_COMLEITURA_COLAB" ON "COMUNICADO_LEITURA" ("ID_COLABORADOR")
  ;

  CREATE INDEX "IDX_EQUIPE_DEPARTAMENTO" ON "EQUIPE" ("ID_DEPARTAMENTO")
  ;

  CREATE INDEX "IDX_EQUIPE_EMPRESA" ON "EQUIPE" ("ID_EMPRESA")
  ;

  CREATE INDEX "IDX_EQMEMBRO_COLAB" ON "EQUIPE_MEMBRO" ("ID_COLABORADOR")
  ;

  CREATE INDEX "FORMACAO_COLAB_COLAB_IX" ON "FORMACAO_COLABORADOR" ("ID_COLABORADOR")
  ;

  CREATE INDEX "FORMACAO_COLAB_EMP_COLAB_IX" ON "FORMACAO_COLABORADOR" ("ID_EMPRESA", "ID_COLABORADOR")
  ;

  CREATE INDEX "FORMACAO_COLAB_VALIDADE_IX" ON "FORMACAO_COLABORADOR" ("ID_EMPRESA", "TP_FORMACAO", "DT_VALIDADE")
  ;

  CREATE INDEX "HISTORICO_CARREIRA_APROV_IX" ON "HISTORICO_CARREIRA" ("ID_APROVADOR")
  ;

  CREATE INDEX "HISTORICO_CARREIRA_CARGO_ANT_IX" ON "HISTORICO_CARREIRA" ("ID_CARGO_ANTERIOR")
  ;

  CREATE INDEX "HISTORICO_CARREIRA_CARGO_NOV_IX" ON "HISTORICO_CARREIRA" ("ID_CARGO_NOVO")
  ;

  CREATE INDEX "HISTORICO_CARREIRA_COLAB_DT_IX" ON "HISTORICO_CARREIRA" ("ID_COLABORADOR", "ST_REGISTRO", "DT_EFETIVA")
  ;

  CREATE INDEX "HISTORICO_CARREIRA_COMUNIC_IX" ON "HISTORICO_CARREIRA" ("ID_COMUNICADO")
  ;

  CREATE INDEX "HISTORICO_CARREIRA_DEP_ANT_IX" ON "HISTORICO_CARREIRA" ("ID_DEPARTAMENTO_ANTERIOR")
  ;

  CREATE INDEX "HISTORICO_CARREIRA_DEP_NOV_IX" ON "HISTORICO_CARREIRA" ("ID_DEPARTAMENTO_NOVO")
  ;

  CREATE INDEX "HISTORICO_CARREIRA_EMP_COLAB_IX" ON "HISTORICO_CARREIRA" ("ID_EMPRESA", "ID_COLABORADOR")
  ;

  CREATE INDEX "HISTORICO_CARREIRA_EMP_DT_IX" ON "HISTORICO_CARREIRA" ("ID_EMPRESA", "DT_EFETIVA")
  ;

  CREATE INDEX "HISTORICO_CARREIRA_GES_ANT_IX" ON "HISTORICO_CARREIRA" ("ID_GESTOR_ANTERIOR")
  ;

  CREATE INDEX "HISTORICO_CARREIRA_GES_NOV_IX" ON "HISTORICO_CARREIRA" ("ID_GESTOR_NOVO")
  ;

  CREATE INDEX "HISTORICO_CARREIRA_TIPO_IX" ON "HISTORICO_CARREIRA" ("ID_TIPO_MOVIMENTACAO")
  ;

  CREATE INDEX "LOG_ACESSO_SAL_COLAB_IX" ON "LOG_ACESSO_SALARIAL" ("ID_COLABORADOR")
  ;

  CREATE INDEX "LOG_ACESSO_SAL_DT_IX" ON "LOG_ACESSO_SALARIAL" ("ID_EMPRESA", SYS_EXTRACT_UTC("DT_CRIACAO"))
  ;

  CREATE INDEX "LOG_ACESSO_SAL_EMP_COLAB_IX" ON "LOG_ACESSO_SALARIAL" ("ID_EMPRESA", "ID_COLABORADOR")
  ;

  CREATE INDEX "LOG_AUDITORIA_CARR_EMP_IX" ON "LOG_AUDITORIA_CARREIRA" ("ID_EMPRESA", SYS_EXTRACT_UTC("DT_CRIACAO"))
  ;

  CREATE INDEX "LOG_AUDITORIA_CARR_REG_IX" ON "LOG_AUDITORIA_CARREIRA" ("NM_TABELA", "ID_REGISTRO")
  ;

  CREATE INDEX "IDX_MOV_COLABORADOR" ON "MOVIMENTACAO_CARREIRA" ("ID_COLABORADOR")
  ;

  CREATE INDEX "SOLICITACAO_CORR_COLAB_IX" ON "SOLICITACAO_CORRECAO" ("ID_COLABORADOR")
  ;

  CREATE INDEX "SOLICITACAO_CORR_EMP_ST_IX" ON "SOLICITACAO_CORRECAO" ("ID_EMPRESA", "ST_SOLICITACAO")
  ;

  CREATE INDEX "SOLICITACAO_CORR_HIST_IX" ON "SOLICITACAO_CORRECAO" ("ID_HISTORICO_CARREIRA")
  ;
