
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_CANAL_FEED" ("ID_CANAL_MENSAGEM", "ID_CANAL", "NOME_CANAL", "ID_EQUIPE", "ID_COLABORADOR", "NOME_AUTOR", "AUTOR_LOGIN", "CORPO", "DATA_ENVIO", "EDITADA", "EXCLUIDA", "STATUS_AUTOR", "QTD_ANEXOS") AS
  SELECT
    m."ID_CANAL_MENSAGEM",
    m."ID_CANAL",
    c."NOME"              AS NOME_CANAL,
    c."ID_EQUIPE",
    m."ID_COLABORADOR",
    col."NOME_COMPLETO"   AS NOME_AUTOR,
    col."LOGIN_APEX"      AS AUTOR_LOGIN,
    m."CORPO",
    m."DATA_ENVIO",
    m."EDITADA",
    m."EXCLUIDA",
    NVL(p."STATUS_PRESENCA", 'OFFLINE') AS STATUS_AUTOR,
    (SELECT COUNT(*) FROM "CANAL_MENSAGEM_ANEXO" a
      WHERE a."ID_CANAL_MENSAGEM" = m."ID_CANAL_MENSAGEM") AS QTD_ANEXOS
FROM "CANAL_MENSAGEM" m
JOIN "CANAL"        c   ON c."ID_CANAL" = m."ID_CANAL"
JOIN "COLABORADOR"  col ON col."ID_COLABORADOR" = m."ID_COLABORADOR"
LEFT JOIN "PRESENCA_COLABORADOR" p ON p."ID_COLABORADOR" = col."ID_COLABORADOR"
WHERE m."EXCLUIDA" = FALSE;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_MINHAS_EQUIPES" ("ID_COLABORADOR", "LOGIN_APEX", "ID_EQUIPE", "NOME_EQUIPE", "ID_EMPRESA", "PAPEL", "ID_CANAL", "NOME_CANAL") AS
  SELECT
    em."ID_COLABORADOR",
    col."LOGIN_APEX",
    e."ID_EQUIPE",
    e."NOME"     AS NOME_EQUIPE,
    e."ID_EMPRESA",
    em."PAPEL",
    c."ID_CANAL",
    c."NOME"     AS NOME_CANAL
FROM "EQUIPE_MEMBRO" em
JOIN "COLABORADOR" col ON col."ID_COLABORADOR" = em."ID_COLABORADOR"
JOIN "EQUIPE"       e  ON e."ID_EQUIPE" = em."ID_EQUIPE" AND e."STATUS" = TRUE
LEFT JOIN "CANAL"    c ON c."ID_EQUIPE" = e."ID_EQUIPE" AND c."STATUS" = TRUE;
