prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/plugin_settings.sql
@@application/shared_components/navigation/lists/emitir_comunicado.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/custom_css.sql
@@application/shared_components/files/custom_min_css.sql
@@application/shared_components/files/default_user_jpeg.sql
@@application/shared_components/files/fotos_ana_pereira_jpg.sql
@@application/shared_components/files/fotos_mariana_oliveira_jpg.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/security/authorizations/equipe_corlix_hub.sql
@@application/shared_components/security/authorizations/publicador_de_conteudo.sql
@@application/shared_components/security/authorizations/somente_diretoria.sql
@@application/shared_components/security/app_access_control/diretoria.sql
@@application/shared_components/security/app_access_control/equipe_do_corlix_hub.sql
@@application/shared_components/security/app_access_control/publicador_de_conteúdo.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/g_nome_usuario.sql
@@application/shared_components/logic/application_items/g_nome_usuario.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/boolean.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/user_interface/templates/button/html_button_legacy_apex_5_migration.sql
@@application/shared_components/user_interface/templates/region/cards_container_image_first.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
